app:
  name: "智学奇境后端服务"
  version: "1.0.0"
  port: 8001
  mode: "development" # development, production

server:
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: "localhost"
  port: 5432
  username: "zhixue_user"
  password: "1024"
  database: "zhixue_db"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: "1h"

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_conns: 5

auth:
  jwt_secret: "zhixue_jwt_secret_1024"
  jwt_expires: "24h"
  refresh_expires: "168h" # 7 days

ai_service:
  url: "http://localhost:8001"
  timeout: "30s"
  retry_count: 3

game_server:
  port: 8002
  websocket: true
  max_connections: 1000

gateway_server:
  port: 8000
  upstreams:
    - name: "auth_service"
      url: "http://localhost:8001"
    - name: "game_service"
      url: "http://localhost:8002"

logging:
  level: "info" # debug, info, warn, error
  file_path: "./logs/zhixue.log"
  max_size: 100 # MB
  max_backups: 30
  max_age: 7 # days
  compress: true
